version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: art-vault-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - art-vault-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '4200:80'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - art-vault-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: bundle exec rails s -b '0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app
      - /app/vendor
    env_file:
      - ./api/.env.production
    depends_on:
      - postgres
    networks:
      - art-vault-network

volumes:
  postgres_data:

networks:
  art-vault-network: