version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: art-vault-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '4200:80'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app
      - /app/vendor
    env_file:
      - ./api/.env
    depends_on:
      - postgres

volumes:
  postgres_data:
